/* Configuration.h - Ender 3 Pro (V4.2.2 STM32) */
#define MOTHERBOARD BOARD_CREALITY_V4
#define EXTRUDERS 1
#define DEFAULT_AXIS_STEPS_PER_UNIT {80,80,400,415}
#define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
